/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-116541-g5dfc0cc841-20240806"
#endif /* AVUTIL_FFVERSION_H */
